id: I92E29232
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T00:37:45+00:00'
last_modified: '2022-06-07T12:27:30.612899+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74215
  title: རབ་གནས་བཀྲ་ཤིས་འབྲིང་པོ།
  author: ''
  base:
    2BB6:
      image_group_id: I4CZ74301
      title: ''
      total_pages: 1072
      order: 1
      base_file: 2BB6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
