id: P000615
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74215
  title: རབ་གནས་བཀྲ་ཤིས་འབྲིང་པོ།
  author: ''
  volumes:
    14acbf43d2534944b82184d63ddcabd0:
      image_group_id: I4CZ74301
      title: ''
      volume_number: 1
      total_pages: 1072
